// Code generated by protoc-gen-go. DO NOT EDIT.
// source: filmepb/filme.proto

package filmepb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Filme struct {
	Movieid              int32    `protobuf:"varint,1,opt,name=movieid,proto3" json:"movieid,omitempty"`
	Title                string   `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Genres               string   `protobuf:"bytes,3,opt,name=genres,proto3" json:"genres,omitempty"`
	Userid               int32    `protobuf:"varint,4,opt,name=userid,proto3" json:"userid,omitempty"`
	Rating               float64  `protobuf:"fixed64,5,opt,name=rating,proto3" json:"rating,omitempty"`
	Timestamp            int64    `protobuf:"varint,6,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Tag                  string   `protobuf:"bytes,7,opt,name=tag,proto3" json:"tag,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Filme) Reset()         { *m = Filme{} }
func (m *Filme) String() string { return proto.CompactTextString(m) }
func (*Filme) ProtoMessage()    {}
func (*Filme) Descriptor() ([]byte, []int) {
	return fileDescriptor_47d4f358c87768c2, []int{0}
}

func (m *Filme) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Filme.Unmarshal(m, b)
}
func (m *Filme) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Filme.Marshal(b, m, deterministic)
}
func (m *Filme) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Filme.Merge(m, src)
}
func (m *Filme) XXX_Size() int {
	return xxx_messageInfo_Filme.Size(m)
}
func (m *Filme) XXX_DiscardUnknown() {
	xxx_messageInfo_Filme.DiscardUnknown(m)
}

var xxx_messageInfo_Filme proto.InternalMessageInfo

func (m *Filme) GetMovieid() int32 {
	if m != nil {
		return m.Movieid
	}
	return 0
}

func (m *Filme) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *Filme) GetGenres() string {
	if m != nil {
		return m.Genres
	}
	return ""
}

func (m *Filme) GetUserid() int32 {
	if m != nil {
		return m.Userid
	}
	return 0
}

func (m *Filme) GetRating() float64 {
	if m != nil {
		return m.Rating
	}
	return 0
}

func (m *Filme) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *Filme) GetTag() string {
	if m != nil {
		return m.Tag
	}
	return ""
}

type ReadFilmesResponse struct {
	Filmes               []*Filme `protobuf:"bytes,1,rep,name=filmes,proto3" json:"filmes,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReadFilmesResponse) Reset()         { *m = ReadFilmesResponse{} }
func (m *ReadFilmesResponse) String() string { return proto.CompactTextString(m) }
func (*ReadFilmesResponse) ProtoMessage()    {}
func (*ReadFilmesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_47d4f358c87768c2, []int{1}
}

func (m *ReadFilmesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadFilmesResponse.Unmarshal(m, b)
}
func (m *ReadFilmesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadFilmesResponse.Marshal(b, m, deterministic)
}
func (m *ReadFilmesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadFilmesResponse.Merge(m, src)
}
func (m *ReadFilmesResponse) XXX_Size() int {
	return xxx_messageInfo_ReadFilmesResponse.Size(m)
}
func (m *ReadFilmesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadFilmesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ReadFilmesResponse proto.InternalMessageInfo

func (m *ReadFilmesResponse) GetFilmes() []*Filme {
	if m != nil {
		return m.Filmes
	}
	return nil
}

type ReadFilmesRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReadFilmesRequest) Reset()         { *m = ReadFilmesRequest{} }
func (m *ReadFilmesRequest) String() string { return proto.CompactTextString(m) }
func (*ReadFilmesRequest) ProtoMessage()    {}
func (*ReadFilmesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_47d4f358c87768c2, []int{2}
}

func (m *ReadFilmesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadFilmesRequest.Unmarshal(m, b)
}
func (m *ReadFilmesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadFilmesRequest.Marshal(b, m, deterministic)
}
func (m *ReadFilmesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadFilmesRequest.Merge(m, src)
}
func (m *ReadFilmesRequest) XXX_Size() int {
	return xxx_messageInfo_ReadFilmesRequest.Size(m)
}
func (m *ReadFilmesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadFilmesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ReadFilmesRequest proto.InternalMessageInfo

func init() {
	proto.RegisterType((*Filme)(nil), "filme.Filme")
	proto.RegisterType((*ReadFilmesResponse)(nil), "filme.ReadFilmesResponse")
	proto.RegisterType((*ReadFilmesRequest)(nil), "filme.ReadFilmesRequest")
}

func init() {
	proto.RegisterFile("filmepb/filme.proto", fileDescriptor_47d4f358c87768c2)
}

var fileDescriptor_47d4f358c87768c2 = []byte{
	// 268 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x90, 0x3d, 0x4b, 0xc4, 0x40,
	0x10, 0x86, 0x5d, 0x63, 0x12, 0x32, 0x2a, 0x9c, 0x73, 0x22, 0xa3, 0x58, 0x84, 0x60, 0x91, 0xea,
	0x84, 0xb3, 0xb3, 0xb4, 0x50, 0x04, 0x6d, 0xd6, 0xee, 0xba, 0xdc, 0x65, 0x0c, 0x0b, 0x97, 0x0f,
	0x77, 0xf6, 0xee, 0x6f, 0xf9, 0x17, 0x25, 0x9b, 0x15, 0x05, 0xad, 0x76, 0x9e, 0x77, 0x3e, 0x76,
	0xde, 0x81, 0xf9, 0xbb, 0xd9, 0xb6, 0x3c, 0xac, 0x6f, 0xfd, 0xbb, 0x18, 0x6c, 0xef, 0x7a, 0x8c,
	0x3d, 0x14, 0x9f, 0x0a, 0xe2, 0xc7, 0x31, 0x42, 0x82, 0xb4, 0xed, 0xf7, 0x86, 0x4d, 0x4d, 0x2a,
	0x57, 0x65, 0xac, 0xbf, 0x11, 0xcf, 0x21, 0x76, 0xc6, 0x6d, 0x99, 0x0e, 0x73, 0x55, 0x66, 0x7a,
	0x02, 0xbc, 0x80, 0xa4, 0xe1, 0xce, 0xb2, 0x50, 0xe4, 0xe5, 0x40, 0xa3, 0xbe, 0x13, 0xb6, 0xa6,
	0xa6, 0x23, 0x3f, 0x26, 0xd0, 0xa8, 0xdb, 0xca, 0x99, 0xae, 0xa1, 0x38, 0x57, 0xa5, 0xd2, 0x81,
	0xf0, 0x1a, 0x32, 0x67, 0x5a, 0x16, 0x57, 0xb5, 0x03, 0x25, 0xb9, 0x2a, 0x23, 0xfd, 0x23, 0xe0,
	0x0c, 0x22, 0x57, 0x35, 0x94, 0xfa, 0x2f, 0xc6, 0xb0, 0xb8, 0x07, 0xd4, 0x5c, 0xd5, 0x7e, 0x69,
	0xd1, 0x2c, 0x43, 0xdf, 0x09, 0xe3, 0x0d, 0x24, 0xde, 0x90, 0x90, 0xca, 0xa3, 0xf2, 0x78, 0x79,
	0xb2, 0x98, 0xcc, 0xfa, 0x32, 0x1d, 0x72, 0xc5, 0x1c, 0xce, 0x7e, 0xf7, 0x7e, 0xec, 0x58, 0xdc,
	0x72, 0x05, 0xa7, 0xaf, 0xa3, 0x53, 0x79, 0x63, 0xbb, 0x37, 0x1b, 0xc6, 0x67, 0x98, 0xbd, 0x18,
	0x71, 0x95, 0x9d, 0xea, 0x9e, 0xec, 0xb0, 0x41, 0x0a, 0xf3, 0xfe, 0xb4, 0x5f, 0x5d, 0xfe, 0x93,
	0x99, 0x96, 0x2a, 0x0e, 0x1e, 0xb2, 0x55, 0x1a, 0x8e, 0xbf, 0x4e, 0xfc, 0xdd, 0xef, 0xbe, 0x02,
	0x00, 0x00, 0xff, 0xff, 0x7d, 0x22, 0x8f, 0x83, 0x8e, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// MoviesServiceClient is the client API for MoviesService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MoviesServiceClient interface {
	ListarFilmesGrpc(ctx context.Context, in *ReadFilmesRequest, opts ...grpc.CallOption) (*ReadFilmesResponse, error)
}

type moviesServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMoviesServiceClient(cc grpc.ClientConnInterface) MoviesServiceClient {
	return &moviesServiceClient{cc}
}

func (c *moviesServiceClient) ListarFilmesGrpc(ctx context.Context, in *ReadFilmesRequest, opts ...grpc.CallOption) (*ReadFilmesResponse, error) {
	out := new(ReadFilmesResponse)
	err := c.cc.Invoke(ctx, "/filme.MoviesService/ListarFilmesGrpc", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MoviesServiceServer is the server API for MoviesService service.
type MoviesServiceServer interface {
	ListarFilmesGrpc(context.Context, *ReadFilmesRequest) (*ReadFilmesResponse, error)
}

// UnimplementedMoviesServiceServer can be embedded to have forward compatible implementations.
type UnimplementedMoviesServiceServer struct {
}

func (*UnimplementedMoviesServiceServer) ListarFilmesGrpc(ctx context.Context, req *ReadFilmesRequest) (*ReadFilmesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListarFilmesGrpc not implemented")
}

func RegisterMoviesServiceServer(s *grpc.Server, srv MoviesServiceServer) {
	s.RegisterService(&_MoviesService_serviceDesc, srv)
}

func _MoviesService_ListarFilmesGrpc_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadFilmesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MoviesServiceServer).ListarFilmesGrpc(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/filme.MoviesService/ListarFilmesGrpc",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MoviesServiceServer).ListarFilmesGrpc(ctx, req.(*ReadFilmesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _MoviesService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "filme.MoviesService",
	HandlerType: (*MoviesServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListarFilmesGrpc",
			Handler:    _MoviesService_ListarFilmesGrpc_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "filmepb/filme.proto",
}
